### ISSUE TITLE
Issues with MacOSX

### ISSUE THREAD

**Issue by natehaxx** [ArtemBogush/DreamcastCdiTool#1]
Hey i got the same Dreamcast like you HKT3030 1PAL , i tried to burn games now serveral times but all the time i want to start the game and press the controller logo the cd stops spinning and the dreamcast restarts any clues ?

**Comment by arthabus** [comment]
Hey @natehaxx - not sure what might be the reason, but I've got similar issue. I ended up buying different CDs till I found one that works. So in my case it came down to the CD manufacturer. Can't suggest any names though as it was some local brand that worked for me.
